### ISSUE TITLE
Android Devices

### ISSUE THREAD

**Issue by david-webber** [BobbyJay/SlaRle.js#2]
This barcode scanner is great, but I've tried using it on several android devices and the canvas is never populated with an image, thus barcode doesnt get scanned.

any hep on this would be great.

**Comment by ghost** [comment]
Hi, this is a limitation by Android and depends on the RAM/Memory and Image Size. If the image is too big and RAM needs to be cleared, the browser gets killed. This causes the page to reload when changing back to the browser. Unfortunately, the image won't be processed.

One fix - not satisfying at all - would be to reduce image size of the camera. Or use getUserMedia() to capture an image, which is supported on Android.
